name: Example

on: ["push"]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode 11.2.1
        run: sudo xcode-select -switch /Applications/Xcode_11.2.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
